services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/backend
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent local node_modules from overwriting container's
    command: ["sh", "/usr/src/app/scripts/start-dev.sh"]
    network_mode: host

  db:
    image: postgres:15-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
