services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent local node_modules from overwriting container's
    command: pnpm start:dev

  db:
    image: postgres:15-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
